/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mx.hammer.gui;

import java.io.File;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileSystemView;
import mx.hammer.entities.Entidades;
import mx.hammer.usb.EUSB;

public class USBE extends javax.swing.JFrame {
    
    private int s,os = 0;
    
    
    public USBE() {
        
        initComponents();
        setLocationRelativeTo(null);
        setSize(440,230);
        jComboBox1.addItem(" Seleccione una opción");
        jComboBox2.addItem(" Seleccione una opción");
        jComboBox2.addItem(" GNU/Linux");
        jComboBox2.addItem(" Windows 7/8/10");
        jComboBox1.setSelectedIndex(0);
        jComboBox2.setSelectedIndex(0);
        
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Encrytor");
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(101, 101, 101));
        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(144, 144, 144));
        jLabel2.setText("OS:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 50, 20));

        jButton1.setBackground(new java.awt.Color(1, 1, 1));
        jButton1.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jButton1.setForeground(new java.awt.Color(144, 144, 144));
        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, 110, -1));

        jButton2.setBackground(new java.awt.Color(1, 1, 1));
        jButton2.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jButton2.setForeground(new java.awt.Color(144, 144, 144));
        jButton2.setText("Salir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 110, -1));

        jLabel3.setBackground(new java.awt.Color(101, 101, 101));
        jLabel3.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(144, 144, 144));
        jLabel3.setText("Dispositivo:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 100, 20));

        jComboBox1.setBackground(new java.awt.Color(1, 1, 1));
        jComboBox1.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(173, 173, 173));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 290, -1));

        jComboBox2.setBackground(new java.awt.Color(1, 1, 1));
        jComboBox2.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jComboBox2.setForeground(new java.awt.Color(173, 173, 173));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 290, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logo/fondo.jpeg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 210));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
        Menu m = new Menu();
        m.setVisible(true); 

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        Entidades ent = new Entidades();
        
        if(os == 0){
        
            if(jComboBox1.getSelectedItem().equals(" Seleccione una opción")|jComboBox2.getSelectedItem().equals(" Seleccione una opción")){

                JOptionPane.showMessageDialog(null, "*** Por favor seleccione un OS y un dispositivo ***");

            }else{

                if(s == 1){

                    String jc = (String) jComboBox1.getSelectedItem();
                    ent.setRutaDevice(jc);
                    EUSB eusb = new EUSB();
                    eusb.lArchivos(ent);
                    eusb.cUSB(ent);
                    jComboBox1.setSelectedIndex(0);
                    JOptionPane.showMessageDialog(null, "*** Archivos encriptados correctamente ***");
                    ent.setSwitchh(0);
                    dispose();
                    Menu m = new Menu();
                    m.setVisible(true); 

                }

                if(s == 2){

                    String jc2 = (String) jComboBox1.getSelectedItem();
                    ent.setRutaDevice(jc2);
                    EUSB eusb = new EUSB();
                    eusb.lArchivos(ent);
                    eusb.dUSB(ent);
                    jComboBox1.setSelectedIndex(0);
                    JOptionPane.showMessageDialog(null, "*** Archivos desencriptados correctamente ***");
                    ent.setSwitchh(0);
                    dispose();
                    Menu m = new Menu();
                    m.setVisible(true); 

                }
            } 
            
        }else{
            
            if(jComboBox1.getSelectedItem().equals(" Seleccione una opción")|jComboBox2.getSelectedItem().equals(" Seleccione una opción")){
            
            JOptionPane.showMessageDialog(null, "*** Por favor seleccione un OS y un dispositivo ***");
            
        }
            
        if(os == 1){
            
            
                if(s == 1){
  
                    ent.setRutaDevice((String)jComboBox1.getSelectedItem());
                    EUSB eusb = new EUSB();
                    eusb.lArchivos(ent);
                    eusb.cUSB(ent);
                    jComboBox1.setSelectedIndex(0);
                    JOptionPane.showMessageDialog(null, "*** Archivos encriptados correctamente ***");
                    ent.setSwitchh(0);
                    dispose();
                    Menu m = new Menu();
                    m.setVisible(true); 

                }

                if(s == 2){
                    
                    ent.setRutaDevice((String) jComboBox1.getSelectedItem());
                    EUSB eusb = new EUSB();
                    eusb.lArchivos(ent);
                    eusb.dUSB(ent);
                    jComboBox1.setSelectedIndex(0);
                    JOptionPane.showMessageDialog(null, "*** Archivos desencriptados correctamente ***");
                    ent.setSwitchh(0);
                    dispose();
                    Menu m = new Menu();
                    m.setVisible(true); 

                }
            }
            
        }
        
    
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed

    Vector<String> vd = new Vector<String>();
    String vd2;
    String path = "/media/";
    int x = 0;
        
        if(jComboBox2.getSelectedItem().equals(" GNU/Linux")){
           jComboBox1.removeAllItems();
           jComboBox1.addItem(" Seleccione una opción");
           jComboBox1.setSelectedIndex(0);
           while(x < 2){
           
                File f = new File(path);

                 if (f.exists()) {

                     File[] arch = f.listFiles();

                     for (int i = 0; i < arch.length; i++) {

                         if (arch[i].isDirectory()) {

                             vd2 = arch[i].getParent() + "/" + arch[i].getName();
                             vd.add(vd2);
                             path = vd2;

                         }

                     }

                 }
                 
               x++;
               
           }
           
                for (int i = 1; i < vd.size(); i++) {
                         
                jComboBox1.addItem(vd.elementAt(i));
                
                }
     
        }
        
        if(jComboBox2.getSelectedItem().equals(" Windows 7/8/10")){
            jComboBox1.removeAllItems();
            jComboBox1.addItem(" Seleccione una opción");
            jComboBox1.setSelectedIndex(0);
            File unidades[] = File.listRoots();
            Entidades ent = new Entidades();
            os = 1;
            String uni;
            for(int i = 0; i < unidades.length; i++)
            {
                
                  
                  jComboBox1.addItem(unidades[i]+"\\"); 
                   
            }

            
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

   
    public void sw(int sw){
        
        this.s = sw;
        
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(USBE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(USBE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(USBE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(USBE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new USBE().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
